Add jsdocs and fix documentation.
digitalbazaar/edv-client pull request #73
Opened 2020-08-24 20:59 UTC by JSAssassin

Note: `jsdoc2md *.js > api.md` doesn't seem to be generating documents for all the `.js` files. I am not sure if I am using it incorrectly or maybe it just doesn't work.

2020-08-25 12:38 UTC, mattcollier commented
@JSAssassin it seems as though you may have been unaware of this outstanding PR from @mandyvenables https://github.com/digitalbazaar/edv-client/pull/71

It appears that she update the jsdocs in large swaths of code as well.  This will of course produce merge conflicts.

@JSAssassin whenever you break ground on a new PR, it's always a good idea to familiarize yourself with any open PRs on the project.  This helps to avoid duplication of effort.

2020-08-25 13:28 UTC, JSAssassin commented
@mattcollier yeah I didn't check the open PRs, sorry about that. I'll keep that in mind and will do next time.

2020-10-28 02:59 UTC, dmitrizagidulin approved these changes
👍 
This is great, more docs is always good.

2020-11-03 15:39 UTC, aljones15 commented
sorry about this one @JSAssassin I guess I should have checked that there is an outstanding PR for jsdocs updates in edv client before noticing it.

2020-11-03 15:44 UTC, aljones15 commented
@mattcollier my apologies about this I noticed some issues with the jsdoc in edv client in [another PR](https://github.com/digitalbazaar/bedrock-web-profile-manager/pull/73) in `web-profile-manager`.

Those issues are still there though:

https://github.com/digitalbazaar/edv-client/blob/4a70c37890a54885f52e5f28cd11b8a4dafab9c1/EdvClient.js#L437-L458

`options.doc` has a type `{string}` for instance, but then there is a check to ensure it an object.

the same issue occurs here:

https://github.com/digitalbazaar/edv-client/blob/4a70c37890a54885f52e5f28cd11b8a4dafab9c1/EdvClient.js#L344-L376

in both cases `options.doc` is documented as a `string` when it should be an object. I might add using a string in both cases will result in an error.

@JSAssassin @dmitrizagidulin

2020-11-03 16:00 UTC, JSAssassin commented
@aljones15 I have fixed the `options.doc` type in jsdocs. Do we need auto api document generation here? 
I tried to set it up, but jsdoc2md *.js > api.md doesn't seem to be working.

2020-11-03 16:23 UTC, aljones15 commented
> @aljones15 I have fixed the `options.doc` type in jsdocs. Do we need auto api document generation here?
> I tried to set it up, but jsdoc2md *.js > api.md doesn't seem to be working.

that has been broken for awhile. I would not worry about it unless specifically assigned to it. Thanks for the doc fix.

2020-11-03 16:53 UTC, aljones15 requested changes
Great work here, just need to clean up the `@typedef` issues and this should be amazing. Thanks alot.

2020-11-03 16:53 UTC, aljones15 commented on EdvClient.js
> -    return this.indexHelper.ensureIndex({attribute, unique});
Are you sure we want to lose this return? I'm pretty confident it doesn't break anything, but would like a search for `ensureIndex` to ensure we are not doing something like:

```js
const foo = edvClient.ensureIndex({attribute});
if(foo) {
  bar();
}
```

2020-11-03 16:53 UTC, aljones15 commented on EdvDocument.js
> +   * @typedef Readable
I like these type defs, but I believe this should be `ReadableStream` and I don't believe you need the typedef unless `ReadableStream` is not imported in this file.

2020-11-03 16:53 UTC, aljones15 commented on EdvDocument.js
> +   * @param {Readable} [options.stream] - A WHATWG Readable stream to read
I'm pretty confident this should be `ReadableStream`

2020-11-03 16:53 UTC, aljones15 commented on EdvClient.js
> +   * @typedef Readable
this probably should be `ReadableStream`. We also might not need the typedef if `ReadableStream` is imported in this file.

2020-11-03 16:53 UTC, aljones15 commented on EdvClient.js
> +   * @typedef https
```suggestion
   *  An object that can make HTTPS requests such as node's https.Agent or ky.
   * @typedef httpsAgent
   * @see https://nodejs.org/api/https.html#https_class_https_agent
```

2020-11-03 16:53 UTC, aljones15 commented on EdvClient.js
> +   * @param {https.Agent} [options.httpsAgent=undefined] - An optional
We are not importing node's `https` library and for good reason (it's backend only). So if you are ok with the change in your typedef above then replace `@param {https.Agent}` with `@param {httpsAgent}`

2020-11-19 21:20 UTC, aljones15 approved these changes
Hey this is an improvement in docs in master so we should probably get this in. 
good work here and thanks for the updates.

2020-11-19 21:25 UTC, merged